set_light_mode:
  name: Set Light Mode
  description: Set the light mode using a raw mode string supported by your spa controller.
  fields:
    spa_id:
      required: true
      example: "12345"
      selector:
        text:
    mode:
      required: true
      example: rainbow
      selector:
        text:

set_light_colour:
  name: Set Light Colour
  description: Set the light colour using a raw colour string supported by your spa controller.
  fields:
    spa_id:
      required: true
      example: "12345"
      selector:
        text:
    colour:
      required: true
      example: blue
      selector:
        text:

set_light_speed:
  name: Set Light Speed
  description: Set animated light speed from 1 to 5.
  fields:
    spa_id:
      required: true
      example: "12345"
      selector:
        text:
    speed:
      required: true
      selector:
        number:
          min: 1
          max: 5

set_blower_mode:
  name: Set Blower Mode
  description: Set blower mode.
  fields:
    spa_id:
      required: true
      selector:
        text:
    mode:
      required: true
      selector:
        select:
          options:
            - off
            - ramp
            - variable

set_blower_speed:
  name: Set Blower Speed
  description: Set blower speed from 1 to 5.
  fields:
    spa_id:
      required: true
      selector:
        text:
    speed:
      required: true
      selector:
        number:
          min: 1
          max: 5
