name: Validate HACS

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
